# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xc < Formula
  desc "Self documenting task runner"
  homepage "https://github.com/joerdav/xc"
  version "0.1.180"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/joerdav/xc/releases/download/v0.1.180/xc_0.1.180_darwin_arm64.tar.gz"
      sha256 "b4bc9b05246cb0483287ce18db411ad5fa45081af9ea7e5ce9be492aff00eedc"

      def install
        bin.install "xc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joerdav/xc/releases/download/v0.1.180/xc_0.1.180_darwin_amd64.tar.gz"
      sha256 "b914e227dc23459bf032ea909a178b535d45d052fd71de15e1ae884392410ea5"

      def install
        bin.install "xc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joerdav/xc/releases/download/v0.1.180/xc_0.1.180_linux_amd64.tar.gz"
      sha256 "f3d3320647db39da6fe03c00647d42fd884d908c006154ed75d59a5d3fa045eb"

      def install
        bin.install "xc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/joerdav/xc/releases/download/v0.1.180/xc_0.1.180_linux_armv7.tar.gz"
      sha256 "556cf55bec51f8c80465589ee1fb7343a2e0248f2603a83685666fbd7a48e0ef"

      def install
        bin.install "xc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joerdav/xc/releases/download/v0.1.180/xc_0.1.180_linux_arm64.tar.gz"
      sha256 "35373d7688736da6f06cd6221cd182937aa00be5b2ed5e05dad768524ef40168"

      def install
        bin.install "xc"
      end
    end
  end
end
