# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xc < Formula
  desc "A cli to eXeCute project tasks from a readme file"
  homepage "https://github.com/Joe-Davidson1802/xc"
  version "0.0.43"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Joe-Davidson1802/xc/releases/download/v0.0.43/xc_0.0.43_darwin_arm64.tar.gz"
      sha256 "c5b32b5af3a7d9525a45cbc758c16525857ecf6ccab2bd135b2ddd183b96d375"

      def install
        bin.install "xc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Joe-Davidson1802/xc/releases/download/v0.0.43/xc_0.0.43_darwin_amd64.tar.gz"
      sha256 "3edc6ff05289213ad81aee66bc4dcb093a7f561a192d45349cf903e254a48996"

      def install
        bin.install "xc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Joe-Davidson1802/xc/releases/download/v0.0.43/xc_0.0.43_linux_armv7.tar.gz"
      sha256 "e71568fae1e5913f9cb041569e7b6429940668cc48f411d0fd94c8194f79dcab"

      def install
        bin.install "xc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Joe-Davidson1802/xc/releases/download/v0.0.43/xc_0.0.43_linux_amd64.tar.gz"
      sha256 "cd85a58a8b87318b992b92651f6180f414907c5ba1880f9793f24c6f06878928"

      def install
        bin.install "xc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Joe-Davidson1802/xc/releases/download/v0.0.43/xc_0.0.43_linux_arm64.tar.gz"
      sha256 "ae92a4f49baa26ccaac8289254a1a78b58a06b95343bb079f487f3a84a48ea13"

      def install
        bin.install "xc"
      end
    end
  end
end
